import {
  Globe,
  Layout,
  Zap,
  TrendingUp,
  Shield,
  Activity,
  RefreshCw,
  Target,
  Terminal,
  BarChart3,
  LucideIcon,
  Cpu,
  FlaskConical,
  Database,
  Layers,
  Search,
  Lock,
  List,
  MessageSquare,
  Monitor,
  Sliders,
  TrendingDown,
  Clock,
} from "lucide-react";

export interface GuideSection {
  id: string;
  title: string;
  icon: LucideIcon;
  image?: string;
  content: string;
}

export const GUIDE_SECTIONS: GuideSection[] = [
  {
    id: "easy-overview",
    title: "Matrix Nedir?",
    icon: Globe,
    image: "/assets/docs/matrix_nedir.png",
    content: `Matrix, sizin yerinize piyasayı 24 saat izleyen dijital bir yardımcıdır. Karmaşık grafikleri basitleştirir ve size ne zaman alıp satmanız gerektiğini söyler.`,
  },
  {
    id: "v5-giga-score",
    title: "GIGA MASTER AI Score",
    icon: Cpu,
    image: "/assets/docs/ai_score_new.png",
    content: `Matrix V5'in kalbidir. Teknik analiz, momentum, hacim ve trend verilerini tek bir devasa formülde birleştirerek işlemin başarı şansını 0-100 arası puanlar.`,
  },
  {
    id: "v5-adaptive-scaling",
    title: "TF-Adaptive Scaling",
    icon: Layers,
    image: "/assets/docs/sistem_katmanlari.png",
    content: `Matrix, baktığınız zaman dilimine (1d, 1h, 4h) göre indikatör hassasiyetlerini otomatik ayarlar. Her TF'de en verimli ölçümü yapar.`,
  },
  {
    id: "easy-architecture",
    title: "Sistem Katmanları",
    icon: Layout,
    image: "/assets/docs/sistem_katmanlari.png",
    content: `Sistem arkada bir çok farklı katman ile çalışır. Balinaları izleyen motor, piyasa havası ve AI karar mekanizması gibi parçalar birleşerek en doğru sonucu üretir.`,
  },
  {
    id: "smc-bos",
    title: "Yapı Kırılımı (BOS)",
    icon: Activity,
    image: "/assets/docs/smc_new.png",
    content: `Fiyatın trend yönünde bir önceki tepeyi veya dibi kırmasıdır. Trendin gücünü ve devamlılığını teyit eder.`,
  },
  {
    id: "smc-choch",
    title: "Karakter Değişimi (CHoCH)",
    icon: RefreshCw,
    image: "/assets/docs/smc_new.png",
    content: `Trendin tersine dönmeye başladığının ilk işaretidir. Erken safhada yön değişikliğini yakalamanızı sağlar.`,
  },
  {
    id: "smc-ob",
    title: "Emir Blokları (Order Blocks)",
    icon: Database,
    image: "/assets/docs/whale_new.png",
    content: `Kurumsal oyuncuların büyük alım/satım emirlerini beklettiği özel bölgelerdir. Fiyat buralardan sert tepki almaya meyillidir.`,
  },
  {
    id: "smc-fvg",
    title: "Fiyat Boşlukları (FVG)",
    icon: Zap,
    image: "/assets/docs/guide_strategy.png",
    content: `Fiyatın çok hızlı hareket edip arkasında bıraktığı dengesizliklerdir. Bu boşluklar fiyat için mıknatıs gibidir, genellikle dolmaya geri dönerler.`,
  },
  {
    id: "smc-liquidity",
    title: "Likidite Avı",
    icon: Target,
    image: "/assets/docs/whale_new.png",
    content: `Amatör yatırımcıların stop seviyelerinin patlatıldığı bölgeleri tespit eder. Balinaların "para topladığı" bu anları size haber verir.`,
  },
  {
    id: "easy-trailing-buy",
    title: "Düştükçe Al (Trailing Buy)",
    icon: Zap,
    image: "/assets/docs/trailing_buy_new.png",
    content: `Fiyat düşerken hemen almaz, düşüşü takip eder. Fiyat en dipten yukarı dönmeye başladığında alım yapar. Böylece her zaman en ucuzdan almayı hedefler.`,
  },
  {
    id: "easy-trailing-sell",
    title: "Yüksekten Sat (Trailing Sell)",
    icon: TrendingUp,
    image: "/assets/docs/trailing_sell_new.png",
    content: `Kâr hedefinize ulaşıldığında hemen satmaz, fiyatın daha da yükselmesini bekler. Fiyat zirveden aşağı dönmeye başladığında satış yaparak kârınızı maksimize eder.`,
  },
  {
    id: "v5-power-loss",
    title: "F4 Güç Kaybı (Power Loss)",
    icon: Activity,
    image: "/assets/docs/regime_new.png",
    content: `Mevcut trendin yorulup yorulmadığını % olarak ölçer. %90 üstü güç kaybı, "yakında geri dönüş geliyor" uyarısıdır.`,
  },
  {
    id: "v5-early-warning",
    title: "Zil Simgesi (Erken Uyarı)",
    icon: Activity,
    image: "/assets/docs/overview.png",
    content: `🔔 Simgesi henüz trend dönmeden ama satıcıların gücü tükendiğinde belirir. "Hazır ol, fırsat yaklaşıyor" demektir.`,
  },
  {
    id: "v5-confirmed-buy",
    title: "Onaylı F4 (Kesin Dönüş)",
    icon: Activity,
    image: "/assets/docs/overview.png",
    content: `✅ Simgesi trendin tamamen döndüğünü ve yeni favori yönün başladığını kanıtlar. En güvenli giriş anıdır.`,
  },
  {
    id: "easy-whale",
    title: "Balina Avcısı",
    icon: Activity,
    image: "/assets/docs/whale_new.png",
    content: `Büyük miktarda para yatıran (Balina) oyuncuların hareketlerini izler. Onlarla birlikte hareket ederek piyasada ezilmenizi engeller.`,
  },
  {
    id: "v5-vpa",
    title: "VPA Analysis",
    icon: BarChart3,
    image: "/assets/docs/overview.png",
    content: `Hacim ve Fiyat arasındaki uyumu ölçer. Gizli alım baskılarını veya "sahte" yükselişleri ortaya çıkarır.`,
  },
  {
    id: "v5-adm",
    title: "Asset Drift Model (ADM)",
    icon: TrendingUp,
    image: "/assets/docs/guide_radar.png",
    content: `Fiyatın bir mıknatıs gibi hangi yöne doğru "sürüklendiğini" istatistiksel modellerle tahmin eder.`,
  },
  {
    id: "easy-regime",
    title: "Piyasa Havası",
    icon: RefreshCw,
    image: "/assets/docs/regime_new.png",
    content: `Piyasanın genel havasını (Güneşli, Bulutlu, Fırtınalı) söyler. Fırtınalı havalarda sizi uyarır ve kaybetmenizi önler.`,
  },
  {
    id: "v5-vol-regime",
    title: "Volatilite Rejimi",
    icon: Activity,
    image: "/assets/docs/guide_market.png",
    content: `Piyasadaki hareketliliği sınıflandırır: NORMAL, SQUEEZE (Sıkışma), EXPLOSION (Patlama). Büyük hareketleri önceden sezer.`,
  },
  {
    id: "v5-squeeze-logic",
    title: "Sıkışma Patlaması (💥)",
    icon: Zap,
    image: "/assets/docs/guide_market.png",
    content: `Fiyat uzun süre dar bir alanda kalınca enerji depolar. 💥 Simgesi bu enerjinin yakında büyük bir yöne boşanacağını haber verir.`,
  },
  {
    id: "easy-stop-loss",
    title: "Zarar Durdur (Trailing SL)",
    icon: Shield,
    image: "/assets/docs/guide_safety.png",
    content: `Fiyat yükseldikçe "Zarar Durdurma" seviyesini de yukarı çeker. Böylece bir kez kâra geçtiğinizde, fiyat düşse bile kârınızın bir kısmını korumuş olursunuz.`,
  },
  {
    id: "easy-breakeven",
    title: "Girişi Koru (Breakeven)",
    icon: Zap,
    image: "/assets/docs/safety.png",
    content: `İlk kârınızı aldıktan sonra, kalan işleminizin riskini sıfıra indirir. Fiyat düşse bile en kötü ihtimalle hiç kayıp yaşamadan işlemden çıkarsınız.`,
  },
  {
    id: "v5-re-entry",
    title: "Tekrar Giriş (Re-Entry)",
    icon: RefreshCw,
    image: "/assets/docs/overview.png",
    content: `Bir coin'i kârla sattıysanız ve fiyat daha uygun bir yerden tekrar alım sinyali verirse, sistem önceki kârınızı masaya koyarak tekrar işleme girer.`,
  },
  {
    id: "v5-insight",
    title: "Matrix Insights (💡)",
    icon: MessageSquare,
    image: "/assets/docs/overview.png",
    content: `İşlem günlüğünde sinyallerin neden üretildiğini insan dilinde açıklar. "Satıcılar yorulduğu için dip yakalandı" gibi mantıklı yorumlar yapar.`,
  },
  {
    id: "easy-wick-protection",
    title: "İğne Koruması",
    icon: Target,
    image: "/assets/docs/guide_safety.png",
    content: `Anlık ve geçici fiyat düşüşlerinde (iğne atma) panikleyip işlemin hemen kapanmasını engeller. Fiyatın kalıcı olarak düştüğünden emin olup öyle karar verir.`,
  },
  {
    id: "op-combat-log",
    title: "Savaş Günlüğü (Combat Log)",
    icon: Terminal,
    image: "/assets/docs/overview.png",
    content: `Sistemin saniye saniye ne düşündüğünü gösteren bir akıştır. Her hesaplama, her tarama ve her karar buraya "Matrix Kodları" gibi düşer.`,
  },
  {
    id: "op-manual-scan",
    title: "Manuel Radar",
    icon: Search,
    image: "/assets/docs/guide_radar.png",
    content: `Mevcut cüzdanınızın dışındaki binlerce fırsatı tek tuşla tarar. Piyasadaki en taze "Matrix V5" sinyallerini önünüze serer.`,
  },
  {
    id: "easy-panic",
    title: "Panik Butonu",
    icon: Zap,
    image: "/assets/docs/safety.png",
    content: `Kötü bir durum olduğunda tek tuşla tüm işlemlerinizi kapatıp paranızı güvenli liman olan dolara (USDT) çevirir.`,
  },
  {
    id: "easy-killswitch",
    title: "Sistem Durdurucu",
    icon: Terminal,
    image: "/assets/docs/safety.png",
    content: `Üst üste birkaç işlem kaybederseniz veya çok fazla işlem yaparsanız sistem sizi korumak için kendini kilitler. "Bugünlük yeter, yarın devam edelim" der.`,
  },
  {
    id: "v5-max-trades",
    title: "Açık İşlem Limiti",
    icon: List,
    image: "/assets/docs/guide_safety.png",
    content: `Cüzdanınızın aşırı risk altına girmemesi için sistemin aynı anda en fazla kaç coine bakabileceğini belirlersiniz.`,
  },
  {
    id: "v5-daily-loss",
    title: "Günlük Zarar Freni",
    icon: TrendingDown,
    image: "/assets/docs/safety.png",
    content: `Piyasa çok kötüyse ve günlük % limitiniz dolduysa sistem "Stop" çeker. Şansı zorlamanızı engeller, kasanızı korur.`,
  },
  {
    id: "v5-signal-freshness",
    title: "Sinyal Tazeliği",
    icon: Clock,
    image: "/assets/docs/overview.png",
    content: `Sistem "eski" sinyalleri çöpe atar. Sadece son birkaç dakika içinde oluşmuş, enerjisi yüksek fırsatlara odaklanır.`,
  },
  {
    id: "easy-radar",
    title: "Para Takibi (BTC Radar)",
    icon: Target,
    image: "/assets/docs/guide_radar.png",
    content: `Paranın Bitcoin'e mi yoksa Altcoinlere mi aktığını izler. Yatırımınızı hangi yöne yapmanız gerektiği konusunda size ipucu verir.`,
  },
  {
    id: "v5-zscore-diamonds",
    title: "Dip Elmasları (💎)",
    icon: Target,
    image: "/assets/docs/overview.png",
    content: `💎 Simgesi fiyatın normalden çok fazla düştüğü ve "gerçek dip" bölgelerine geldiği anlarda belirir.`,
  },
  {
    id: "easy-decay",
    title: "Taze Sinyaller",
    icon: RefreshCw,
    image: "/assets/docs/overview.png",
    content: `Eski ve bayatlamış sinyallerle işlem yapmanızı engeller. Her zaman taze ve güncel fırsatları önünüze getirir.`,
  },
  {
    id: "easy-bayesian",
    title: "Olasılık Takibi",
    icon: BarChart3,
    image: "/assets/docs/guide_ai.png",
    content: `Sistemin geçmiş verilerine bakarak o anki işlemin tutma olasılığını hesaplar. Size "bu işlemin başarı ihtimali yüksek" veya "riskli" şeklinde bilgi verir.`,
  },
  {
    id: "easy-bridge",
    title: "Köprü Kurulumu",
    icon: Layout,
    image: "/assets/docs/overview.png",
    content: `Sistemin kesintisiz çalışması için tarayıcınıza kurduğunuz küçük bir yardımcıdır. Teknik verilerin anlık ve hızlı gelmesini sağlar.`,
  },
  {
    id: "easy-test-mode",
    title: "Sanal Para (Test Modu)",
    icon: Terminal,
    image: "/assets/docs/regime_new.png",
    content: `Kendi paranızı riske atmadan önce sistem size 100.000$ sanal para verir. Burada antrenman yapıp kendinize güvendiğinizde gerçek paraya geçebilirsiniz.`,
  },
  {
    id: "easy-smc",
    title: "Piyasa İskeleti (SMC)",
    icon: Layout,
    image: "/assets/docs/smc_new.png",
    content: `Fiyatın hangi yöne kırıldığını (yukarı mı aşağı mı) otomatik tespit eder. Bir binanın iskeleti gibi, piyasanın sağlam basıp basmadığını gösterir.`,
  },
  {
    id: "v5-premium-discount",
    title: "Pahalı/Ucuz Bölgeler",
    icon: Sliders,
    image: "/assets/docs/overview.png",
    content: `SMC mantığına göre grafik üzerinde Premium (Satış) ve Discount (Alım) bölgelerini boyar. Yanlış yerden işleme girmenizi önler.`,
  },
  {
    id: "easy-ob-legend",
    title: "Kurumsal Seviyeler",
    icon: Target,
    image: "/assets/docs/whale_new.png",
    content: `Bankaların ve büyük borsaların alım emri beklettiği bölgeleri boyayarak gösterir. Fiyat buralardan tepki almaya meyillidir.`,
  },
  {
    id: "easy-volatility",
    title: "Piyasa Hızı",
    icon: Activity,
    image: "/assets/docs/guide_market.png",
    content: `Piyasa şu an çok mu hızlı (patlamaya hazır) yoksa çok mu yavaş (uykuda) olduğunu söyler. Doğru zamanda işlemde olmanızı sağlar.`,
  },
  {
    id: "easy-zscore",
    title: "Lastik Etkisi (Z-Score)",
    icon: RefreshCw,
    image: "/assets/docs/guide_market.png",
    content: `Fiyatın ortlamadan çok fazla uzaklaşıp uzaklaşmadığını ölçer. Fazla çekilmiş bir lastik gibi, fiyatın ne zaman geri döneceğini tahmin etmenize yardım eder.`,
  },
  {
    id: "v5-funding-impact",
    title: "Fonlama Etkisi",
    icon: Target,
    image: "/assets/docs/growth.png",
    content: `MEXC Futures'daki fonlama faizlerini izler. Eğer faiz çok yüksekse, terste kalmamanız için sizi uyarır.`,
  },
  {
    id: "easy-capital",
    title: "Para Akışı",
    icon: Target,
    image: "/assets/docs/growth.png",
    content: `Paranın hangi altcoin gruplarına aktığını izler. Hangi trendlerin yükselişte olduğunu erkenden fark etmenizi sağlar.`,
  },
  {
    id: "easy-fvg-gap",
    title: "Fiyat Boşlukları (FVG)",
    icon: Zap,
    image: "/assets/docs/guide_strategy.png",
    content: `Fiyatın çok hızlı hareket edip arkasında bıraktığı boşluklardır. Fiyat genellikle bu boşlukları doldurmak için geri döner. Bir nevi "mıknatıs" görevi görürler.`,
  },
  {
    id: "easy-alarms",
    title: "Anlık Bildirimler",
    icon: Activity,
    image: "/assets/docs/safety.png",
    content: `Ekran başında olmanıza gerek yok. Önemli bir hareket olduğunda sistem cebinize veya bilgisayarınıza anında haber uçurur.`,
  },
  {
    id: "ui-command-bar",
    title: "Command Bar (⌨️)",
    icon: Terminal,
    image: "/assets/docs/overview.png",
    content: `Terminalin altındaki hızlı paneldir. "Yeni İşlem", "Her Şeyi Sat", "Pilot Ayarları" gibi kritik komutlara saniyeler içinde erişirsiniz.`,
  },
  {
    id: "easy-scalp",
    title: "Hızlı Kazanç (Scalp)",
    icon: Zap,
    image: "/assets/docs/guide_strategy.png",
    content: `Çok kısa süreli, dakikalık grafiklerde yapılan hızlı al-sat işlemleridir. Küçük ama sık kârlar kovalamayı sevenler içindir.`,
  },
  {
    id: "easy-swing",
    title: "Büyük Dalga (Swing)",
    icon: TrendingUp,
    image: "/assets/docs/guide_strategy.png",
    content: `Günlerce veya haftalarca süren büyük trendleri yakalamayı hedefler. Daha az işlem yapıp, daha büyük hareketleri bekleyenler için idealdir.`,
  },
  {
    id: "easy-performance",
    title: "Başarı Takibi",
    icon: BarChart3,
    image: "/assets/docs/growth.png",
    content: `Sistem her 4 saatte bir kasanızın fotoğrafını çeker. Hangi günler kâr, hangi günler zarar ettiğinizi bir karne gibi önünüze koyar.`,
  },
  {
    id: "ui-horizon-layout",
    title: "Horizon Layout",
    icon: Layout,
    image: "/assets/docs/overview.png",
    content: `Gelecekçi, siyah tabanlı ve siberpunk tasarımıyla tüm verileri tek bir ufuk çizgisinde toplar. Göz yormaz, dikkati uyanık tutar.`,
  },
  {
    id: "easy-limit",
    title: "Sıraya Gir (Limit)",
    icon: Layout,
    image: "/assets/docs/smc_new.png",
    content: `İstediğiniz fiyata alış veya satış emri bırakmanızı sağlar. Market fiyatı oraya gelene kadar sabırla bekler.`,
  },
  {
    id: "easy-market",
    title: "Hemen Al (Market)",
    icon: Zap,
    image: "/assets/docs/guide_strategy.png",
    content: `Fiyatı beklemeden, o an piyasada en iyi ne fiyat varsa oradan alım veya satım yapar. Hızın önemli olduğu anlar içindir.`,
  },
  {
    id: "ui-smart-trade-grid",
    title: "Hızlı Emir Grid",
    icon: List,
    image: "/assets/docs/overview.png",
    content: `Aktif işlemlerinizi şık kutucuklar halinde listeler. Kâr durumunuzu ve MTF sinyallerini buradan canlı takip edersiniz.`,
  },
  {
    id: "easy-split-tp",
    title: "Parça Parça Kazanç",
    icon: BarChart3,
    image: "/assets/docs/growth.png",
    content: `Tüm malınızı tek bir fiyatta satmak yerine, fiyat yükseldikçe kademeli olarak satmanızı sağlar. Kârınızı garanti altına alır.`,
  },
  {
    id: "easy-timeout",
    title: "Tuzak Koruması (Timeout)",
    icon: Shield,
    image: "/assets/docs/guide_safety.png",
    content: `Fiyat anlık olarak "Zarar Durdur" seviyenize değip hemen geri çıkarsa, sistem sizi hemen oyundan atmaz. Birkaç saniye bekler ve bunun bir tuzak olup olmadığını anlar.`,
  },
  {
    id: "v5-pilot-executor",
    title: "Pilot Executor",
    icon: Activity,
    image: "/assets/docs/regime_new.png",
    content: `Otopilotun kalbidir. Sinyal geldiğinde bakiyenizi kontrol eder, emri borsaya iletir, takibini yapar ve her adımı size raporlar.`,
  },
  {
    id: "easy-tech-panel",
    title: "Durum Özeti",
    icon: Terminal,
    image: "/assets/docs/guide_market.png",
    content: `Ekranın bir köşesinde piyasanın o anki fotoğrafını çeker. Trend ne yönde, güç ne durumda hepsini bir bakışta görürsünüz.`,
  },
  {
    id: "easy-decision",
    title: "Sistemin Son Sözü",
    icon: Target,
    image: "/assets/docs/guide_ai.png",
    content: `Onlarca karmaşık hesaplamadan sonra sistem size tek bir kelime söyler: "İŞLEM AÇ" veya "BEKLE". Size sadece uymak kalır.`,
  },
  {
    id: "easy-simulator",
    title: "Eğitim Simülatörü",
    icon: Terminal,
    image: "/assets/docs/overview.png",
    content: `Geçmişte piyasa nasıl hareket etmiş, sistem orada ne yapmış görebilirsiniz. Kendi stratejinizi geliştirmek için harika bir antrenman sahasıdır.`,
  },
  {
    id: "ui-mtf-matrix",
    title: "MTF Karar Matrisi",
    icon: Monitor,
    image: "/assets/docs/overview.png",
    content: `5 farklı zaman dilimini (1d'den 1h'ye) tek satırda birleştirir. Tüm zamanlar "Yeşil" ise gemiye binme vaktidir.`,
  },
  {
    id: "easy-mtf-icons",
    title: "MTF Analizi Simgeleri",
    icon: Activity,
    image: "/assets/docs/overview.png",
    content: `MTF (Çoklu Zaman Dilimi) kutularının altında o anki duruma göre çeşitli simgeler belirir. ✅ F4 Dönüş Onayını; 🔔 F4 Güç Kaybı uyarısını; 🐋 Balina Hareketini; 💎 Aşırı Ucuzluk (Dip) bölgesini; 🔥 Aşırı Şişmiş (Tepe) bölgesini; 💥 ise büyük bir patlama öncesi Sıkışmayı ifade eder. Sadece '-' (Tire) görüyorsanız piyasa aşırı durgun ve nötr demektir.`,
  },
];
