//@version=5
strategy("Karpathy Otonom Stratejisi", shorttitle="KOS", overlay=true, format=format.price, precision=2)
length = input(14, title="Uzunluk")
src = close
sma = ta.sma(src, length)
longCondition = ta.crossover(src, sma)
shortCondition = ta.crossunder(src, sma)
if (longCondition)
    strategy.entry("Long", strategy.long)
if (shortCondition)
    strategy.entry("Short", strategy.short)
// Take Profit ve Stop Loss ayarları
takeProfitPct = input.float(1.1, title="Take Profit Oranı")
stopLossPct = input.float(1.3, title="Stop Loss Oranı")
strategy.exit("Long Exit", "Long", stop=close * (1 - stopLossPct / 100), limit=close * (1 + takeProfitPct / 100))
strategy.exit("Short Exit", "Short", stop=close * (1 + stopLossPct / 100), limit=close * (1 - takeProfitPct / 100))